apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  labels:
    app: external-dns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.5
        args:
        - --provider=cloudflare
        - --cloudflare-proxied
        - --source=ingress
        - --domain-filter=$(DOMAIN_FILTER)
        - --namespace=$(POD_NAMESPACE)
        env:
        - name: DOMAIN_FILTER
          value: karc.io
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: origin-ca-key
              key: cf-api-key
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: origin-ca-key
              key: cf-api-email
        resources:
          limits:
            cpu: 100m
            memory: 200Mi