kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    route:
      group_by: ['alertname', 'job']

      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

      receiver: discord
    receivers:
    - name: discord
      discord_configs:
      - webhook_url: <url>
