---
- name: Create directory for config file
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  become: true
  loop:
    - /etc/rancher/
    - /etc/rancher/k3s/

- name: Create registry config file
  template:
    src: registry_config_template.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
  become: true

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Run expect to wait for a successful PXE boot via out-of-band CIMC
  ansible.builtin.shell: |
    sudo iptables -P INPUT ACCEPT
    sudo iptables -P FORWARD ACCEPT
    sudo iptables -P OUTPUT ACCEPT
    sudo iptables -F

    exit 0
