---
- name: Instalar pacotes via pip3
  ansible.builtin.pip:
    name:
      - kubernetes>=12.0.0
      - PyYAML>=3.11
      - jsonpatch
    executable: pip3

- name: Add longhorn chart repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: "https://charts.longhorn.io"
    kubeconfig: ../../../kubeconfig

- name: Add istio chart repo
  kubernetes.core.helm_repository:
    name: istio
    repo_url: "https://istio-release.storage.googleapis.com/charts"
    kubeconfig: ../../../kubeconfig

- name: Add kong Helm repo and update
  kubernetes.core.helm_repository:
    name: kong
    repo_url: https://charts.konghq.com
    kubeconfig: ../../../kubeconfig

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
    kubeconfig: ../../../kubeconfig

- name: Deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig: ../../../kubeconfig

- name: Patch storageclass local-path
  kubernetes.core.k8s:
    kubeconfig: ../../../kubeconfig
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: local-path
    merge_type:
      - merge
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"

- name: Sleep for 30 seconds
  ansible.builtin.wait_for:
    timeout: 30
- name: Patch storageclass longhorn
  kubernetes.core.k8s:
    kubeconfig: ../../../kubeconfig
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: longhorn
    merge_type:
      - merge
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
  retries: 30
  delay: 10

- name: Install istio-base
  kubernetes.core.helm:
    name: istio-base
    chart_ref: istio/base
    release_namespace: istio-system
    create_namespace: true
    kubeconfig: ../../../kubeconfig
    values:
      defaultRevision: default

- name: Install istiod
  kubernetes.core.helm:
    name: istiod
    chart_ref: istio/istiod
    release_namespace: istio-system
    create_namespace: true
    kubeconfig: ../../../kubeconfig
    wait: yes

- name: Create kong-istio namespace
  kubernetes.core.k8s:
    name: kong-istio
    kind: Namespace
    state: present
    kubeconfig: ../../../kubeconfig

- name: Label kong-istio namespace for istio injection
  kubernetes.core.k8s:
    kubeconfig: ../../../kubeconfig
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kong-istio
        labels:
          istio-injection: enabled
    state: present

- name: Install kong
  kubernetes.core.helm:
    name: kong-istio
    chart_ref: kong/kong
    release_namespace: kong-istio
    create_namespace: true
    kubeconfig: ../../../kubeconfig
    wait: yes
