{
    "changed": false,
    "failed": false,
    "method": "update",
    "result": {
        "apiVersion": "v1",
        "data": {
            "cf-api-email": "cmthcmNhcHBzQGdtYWlsLmNvbQ==",
            "cf-api-key": "djEuMC0xMDA0ODE5YTFmNGYzOWM5ZGIyMmY2NDItOGZhMjA4Y2E2MDAyNTI3MzIyYWYyYzI2YjcyMTc1NjYzY2U2ZWEwMWFiNmVlMThlOTAwMWExM2UwZWYxYjc3MWZiYzI0YjFkNGEwMjJkYjE1YTM4MDRkOWJmZjg4OGMxMzE3MTU0NGE1ZjJjZjY5MmRmZTkxMzJjMTY0YjYzYTgxY2UzNDdiZThhM2E3N2VlYjU="
        },
        "kind": "Secret",
        "metadata": {
            "creationTimestamp": "2023-08-20T21:52:53Z",
            "managedFields": [
                {
                    "apiVersion": "v1",
                    "fieldsType": "FieldsV1",
                    "fieldsV1": {
                        "f:data": {
                            ".": {},
                            "f:cf-api-email": {},
                            "f:cf-api-key": {}
                        },
                        "f:type": {}
                    },
                    "manager": "OpenAPI-Generator",
                    "operation": "Update",
                    "time": "2023-08-20T21:52:53Z"
                }
            ],
            "name": "origin-ca-key",
            "namespace": "prod-issuer",
            "resourceVersion": "465646",
            "uid": "46d23dbc-0c6a-4d3b-9fbc-ba0456c6597a"
        },
        "type": "Opaque"
    }
}