---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

- hosts: localhost
  connection: local
  roles:
    - role: post